### ISSUE TITLE
Pattern 'n' failed!

### ISSUE THREAD

**Issue by Zenkyou** [QuickNET-Tech/Universal_GTAO_Booster#1] opened 2021-03-06 15:38 UTC
As soon as I inject the .dll into the game process (GTA5.exe) I got this error.
Im injecting while the game is in the first screen (where you choose to go online or Story mode)
![image](https://user-images.githubusercontent.com/28145717/110212160-d0d92880-7e78-11eb-8b61-467b4e8f6d4f.png)

Windows 10 20h2.

**Comment by Cloudhunter** [comment] 2021-03-06 21:26
What platform are you running the game on? Epic, Rockstar Launcher, Steam?

**Comment by QuickNET-Tech** [comment] 2021-03-07 01:41
First thing I'd suggest doing is verifying your game files.
Also, platform would be helpful like Cloudhunter mentioned.

**Comment by QuickNET-Tech** [comment] 2021-03-09 14:38
Unable to reproduce and issue opener hasn't responded. Closing issue.

**Comment by Zenkyou** [comment] 2021-03-09 21:56
Games files verified.
Plataform is Epic Games.
Im using Extreme Injector v3.
Error is now this
![image](https://user-images.githubusercontent.com/28145717/110543432-14e25c80-8109-11eb-9e5e-48daea49f7c9.png)


Sorry for the delay.

**Comment by QuickNET-Tech** [comment] 2021-03-09 22:00
Thank you, will see if I can figure out the issue, EGS *should* be identical to the RGL version, guess I'll need to double check that.

**Comment by Zenkyou** [comment] 2021-03-09 22:32
Yes, just the pure GTAV V

**Comment by Zenkyou** [comment] 2021-03-09 22:48
![image](https://user-images.githubusercontent.com/28145717/110549115-5aeeee80-8110-11eb-861c-e9f813670774.png)
![image](https://user-images.githubusercontent.com/28145717/110549148-67734700-8110-11eb-84e9-a60c975a59bc.png)
![image](https://user-images.githubusercontent.com/28145717/110549168-6cd09180-8110-11eb-8996-33ff31fb761d.png)
![image](https://user-images.githubusercontent.com/28145717/110549182-722ddc00-8110-11eb-8121-76b996c89a87.png)

**Comment by QuickNET-Tech** [comment] 2021-03-09 23:05
Something is super wrong, there's no way every single pattern fails like that, especially since in a dump of the EGS version I can find all the patterns. 

Only thing that comes to mind though is an anti-virus interfering.

**Comment by Zenkyou** [comment] 2021-03-09 23:38
I have Malwarebytes installed, but it is currently closed.
Windows Defender realtime protection is disabled.
UAC level is set to lowest.

**Comment by Zenkyou** [comment] 2021-03-09 23:45
![image](https://user-images.githubusercontent.com/28145717/110553482-c9837a80-8117-11eb-8c5d-0efad6fa69c1.png)
I changed the injector from "Extreme Injector v3" to "RemoteDLL" (it is the name of the injector) and it worked I think.

**Comment by QuickNET-Tech** [comment] 2021-03-09 23:48
Looks like it's working to me, interesting that changing the DLL injector made a difference.

**Comment by Zenkyou** [comment] 2021-03-09 23:51
It is indeed working. Less 3 minutes loading time..
Thank you very much.

**Closed** 2021-03-10 00:34 UTC
